### ISSUE TITLE
Research BOINC containers

### ISSUE THREAD

**Issue by grctest** [Erkan-Yilmaz/Gridcoin-tasks#109]
>[LokoToki wrote](https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/105#issuecomment-293809209):
>> What would be great would be a stand-alone account manager, like a local Boincstats BAM! on your computer, so you'd be in charge of all your own keys.
>
> It would be another "app" the user have to install. But what if we think a bit further. Imagine a Secure Boinc Manager which encapsulate the native BOINC Manager in a secure environment that uses the Project Manager interface from the Boinc Manager - like a virtual machine. It's open source. So instead of one App u install another app including Password Manager and multi machine remote management like boinc task. Than the dev has nearly unlimited possibilities.

Potential candidate software:
https://www.projectatomic.io/

**Comment by tomasbrod** [comment]
On linux this is already done. Boinc runs as separate user.
