### ISSUE TITLE
Improve upon client translations! (23 unsupported languages!)

### ISSUE THREAD

**Issue by grctest** [Erkan-Yilmaz/Gridcoin-tasks#111]
I believe that getting the Gridcoin client translated to Chinese (Cantonese/Mandarin) is a high priority - getting added to a Chinese exchange won't happen without language support.

As well as Chinese there are 23 other languages with incomplete translation entries, this is not ok considering our community is distributed around the world. The unsupported languages show '???' throughout the client despite being an available option in the language drop-down menu.

Until we have full translations, I believe it would be far more professional to simply not display unsupported languages within the drop-down menu

Can we get some volunteers to provide translations? It would be major kudos within the community! In the mean time we should consider placing bounties on full translations and look towards similar cryptocurrencies for quick translation inheritance (gives us a head start).

Affected files:
Gridcoin:[ar](https://github.com/gridcoin/Gridcoin-Research/blob/master/src/qt/locale/bitcoin_ar.ts) ; Blackcoin:[ar](https://github.com/CoinBlack/blackcoin/blob/v1.2.4/src/qt/locale/bitcoin_ar.ts)
Gridcoin:[be_BY](https://github.com/gridcoin/Gridcoin-Research/blob/master/src/qt/locale/bitcoin_be_BY.ts) ; Blackcoin:[be_BY](https://github.com/CoinBlack/blackcoin/blob/v1.2.4/src/qt/locale/bitcoin_be_BY.ts)
Gridcoin:[bg](https://github.com/gridcoin/Gridcoin-Research/blob/master/src/qt/locale/bitcoin_bg.ts) ; Blackcoin:[bg](https://github.com/CoinBlack/blackcoin/blob/v1.2.4/src/qt/locale/bitcoin_bg.ts)
Gridcoin:[el_GR](https://github.com/gridcoin/Gridcoin-Research/blob/master/src/qt/locale/bitcoin_el_GR.ts) ; Blackcoin:[el_GR](https://github.com/CoinBlack/blackcoin/blob/v1.2.4/src/qt/locale/bitcoin_el_GR.ts)
Gridcoin:[fa](https://github.com/gridcoin/Gridcoin-Research/blob/master/src/qt/locale/bitcoin_fa.ts) ; Blackcoin:[fa](https://github.com/CoinBlack/blackcoin/blob/v1.2.4/src/qt/locale/bitcoin_fa.ts)
Gridcoin:[fa_IR](https://github.com/gridcoin/Gridcoin-Research/blob/master/src/qt/locale/bitcoin_fa_IR.ts) ; Blackcoin:[fa_IR](https://github.com/CoinBlack/blackcoin/blob/v1.2.4/src/qt/locale/bitcoin_fa_IR.ts)
Gridcoin:[he](https://github.com/gridcoin/Gridcoin-Research/blob/master/src/qt/locale/bitcoin_he.ts) ; Blackcoin:[he](https://github.com/CoinBlack/blackcoin/blob/v1.2.4/src/qt/locale/bitcoin_he.ts)
Gridcoin:[hi_IN](https://github.com/gridcoin/Gridcoin-Research/blob/master/src/qt/locale/bitcoin_hi_IN.ts) ; Blackcoin:[hi_IN](https://github.com/CoinBlack/blackcoin/blob/v1.2.4/src/qt/locale/bitcoin_hi_IN.ts)
Gridcoin:[ja](https://github.com/gridcoin/Gridcoin-Research/blob/master/src/qt/locale/bitcoin_ja.ts) ; Blackcoin:[ja](https://github.com/CoinBlack/blackcoin/blob/v1.2.4/src/qt/locale/bitcoin_ja.ts)
Gridcoin:[ka](https://github.com/gridcoin/Gridcoin-Research/blob/master/src/qt/locale/bitcoin_ka.ts) ; Blackcoin:[ka](https://github.com/CoinBlack/blackcoin/blob/v1.2.4/src/qt/locale/bitcoin_ka.ts)
Gridcoin:[kk_KZ](https://github.com/gridcoin/Gridcoin-Research/blob/master/src/qt/locale/bitcoin_kk_KZ.ts) ; Blackcoin:[kk_KZ](https://github.com/CoinBlack/blackcoin/blob/v1.2.4/src/qt/locale/bitcoin_kk_KZ.ts)
Gridcoin:[ko_KR](https://github.com/gridcoin/Gridcoin-Research/blob/master/src/qt/locale/bitcoin_ko_KR.ts) ; Blackcoin:[ko_KR](https://github.com/CoinBlack/blackcoin/blob/v1.2.4/src/qt/locale/bitcoin_ko_KR.ts)
Gridcoin:[ky](https://github.com/gridcoin/Gridcoin-Research/blob/master/src/qt/locale/bitcoin_ky.ts) ; Blackcoin:[ky](https://github.com/CoinBlack/blackcoin/blob/v1.2.4/src/qt/locale/bitcoin_ky.ts)
Gridcoin:[ro_RO](https://github.com/gridcoin/Gridcoin-Research/blob/master/src/qt/locale/bitcoin_ro_RO.ts) ; Blackcoin:[ro_RO](https://github.com/CoinBlack/blackcoin/blob/v1.2.4/src/qt/locale/bitcoin_ro_RO.ts)
Gridcoin:[sah](https://github.com/gridcoin/Gridcoin-Research/blob/master/src/qt/locale/bitcoin_sah.ts) ; Blackcoin:[sah](https://github.com/CoinBlack/blackcoin/blob/v1.2.4/src/qt/locale/bitcoin_sah.ts)
Gridcoin:[sr](https://github.com/gridcoin/Gridcoin-Research/blob/master/src/qt/locale/bitcoin_sr.ts) ; Blackcoin:[sr](https://github.com/CoinBlack/blackcoin/blob/v1.2.4/src/qt/locale/bitcoin_sr.ts)
Gridcoin:[th_TH](https://github.com/gridcoin/Gridcoin-Research/blob/master/src/qt/locale/bitcoin_th_TH.ts) ; Blackcoin:[th_TH](https://github.com/CoinBlack/blackcoin/blob/v1.2.4/src/qt/locale/bitcoin_th_TH.ts)
Gridcoin:[tr](https://github.com/gridcoin/Gridcoin-Research/blob/master/src/qt/locale/bitcoin_tr.ts) ; Blackcoin:[tr](https://github.com/CoinBlack/blackcoin/blob/v1.2.4/src/qt/locale/bitcoin_tr.ts)
Gridcoin:[uk](https://github.com/gridcoin/Gridcoin-Research/blob/master/src/qt/locale/bitcoin_uk.ts) ; Blackcoin:[uk](https://github.com/CoinBlack/blackcoin/blob/v1.2.4/src/qt/locale/bitcoin_uk.ts)
Gridcoin:[ur ; Blackcoin:PK](https://github.com/gridcoin/Gridcoin-Research/blob/master/src/qt/locale/bitcoin_ur_PK.ts) ; Blackcoin:[ur ; Blackcoin:PK](https://github.com/CoinBlack/blackcoin/blob/v1.2.4/src/qt/locale/bitcoin_ur_PK.ts)
Gridcoin:[vi](https://github.com/gridcoin/Gridcoin-Research/blob/master/src/qt/locale/bitcoin_vi.ts) ; Blackcoin:[vi](https://github.com/CoinBlack/blackcoin/blob/v1.2.4/src/qt/locale/bitcoin_vi.ts)
Gridcoin:[zh_CN](https://github.com/gridcoin/Gridcoin-Research/blob/master/src/qt/locale/bitcoin_zh_CN.ts) ; Blackcoin:[zh_CN](https://github.com/CoinBlack/blackcoin/blob/v1.2.4/src/qt/locale/bitcoin_zh_CN.ts)
Gridcoin:[zh_TW](https://github.com/gridcoin/Gridcoin-Research/blob/master/src/qt/locale/bitcoin_zh_TW.ts) ; Blackcoin:[zh_TW](https://github.com/CoinBlack/blackcoin/blob/v1.2.4/src/qt/locale/bitcoin_zh_TW.ts)
Gridcoin:[fa](https://github.com/gridcoin/Gridcoin-Research/blob/master/src/qt/locale/bitcoin_fa.ts) ; Blackcoin:[fa](https://github.com/CoinBlack/blackcoin/blob/v1.2.4/src/qt/locale/bitcoin_fa.ts)

Reference: (includes non-affected translations)
![image](https://cloud.githubusercontent.com/assets/15861527/25073080/51fedc0a-22d6-11e7-9406-755e84c2d897.png)

**Comment by PsiPhiTheta** [comment]
Guys I am willing to do the entire french translation. Can someone send me a list of all the words to translate for Gridcoin? (I'll have a look at the Blackcoin translation, review and alter it where necessary)

**Comment by grctest** [comment]
> Guys I am willing to do the entire french translation. Can someone send me a list of all the words to translate for Gridcoin? (I'll have a look at the Blackcoin translation, review and alter it where necessary)
>
>It looks like French has not been linked in anyway - has it already been done?

https://github.com/gridcoin/Gridcoin-Research/blob/master/src/qt/locale/bitcoin_fr.ts
https://github.com/gridcoin/Gridcoin-Research/blob/master/src/qt/locale/bitcoin_fr_CA.ts

It would appear that French has already been translated, you could always perform a review of the translations in an effort to improve existing translations?

Thanks 👍

**Comment by tomasbrod** [comment]
I am here for the sk_SK translation. Even if only 5 people will actually use it, haha. It is present, but broken. What encoding is being used, Unicode UTF-8? Looks like all `ť` got replaced by `?`.

**Comment by PsiPhiTheta** [comment]
> It would appear that French has already been translated, you could always perform a review of the translations in an effort to improve existing translations?

Done.

**Comment by grctest** [comment]
> I am here for the sk_SK translation. Even if only 5 people will actually use it, haha. It is present, but broken. What encoding is being used, Unicode UTF-8? Looks like all ť got replaced by ?.

I believe something similar occurred for the Hungarian translation (fixed recently by a community member), if you're able to substitute the '?' character with the appropriate character that would be excellent. If there are multiple '???' characters in a row that means the translation wasn't supplied in the first place.

Something else I've spotted is that throughout the translations we are missing copyright credits to blackcoin for their work done after peercoin (and before gridcoin).

**Comment by JovanDj** [comment]
I will do the sr translation. Do I pull the file then push the translated file?

**Comment by grctest** [comment]
>I will do the sr translation. Do I fork the file then push the translated file?

Yeah, create a fork of the [Gridcoin-Research](https://github.com/gridcoin/Gridcoin-Research/) repo, change the files then submit a [pull request](https://github.com/gridcoin/Gridcoin-Research/pulls). Thanks for helping 👍

**Comment by grctest** [comment]
>`<translation type="unfinished"></translation>`
>`<translation type="unfinished"/>`

The above are also used instead of "???" To identify a lack of translations.

**Comment by denravonska** [comment]
Everyone translating should use [Qt Linguist](http://doc.qt.io/qt-5/qtlinguist-index.html) to make it easier to translate and to ensure that nothing is missed. Also, use the language files from the development branch, which just got rescanned.

**Comment by tomasbrod** [comment]
The problem with Qt Linguist is that it has all translations marked as done. Even the broken ones and I did not find how to mark all non-done. So it does not really help.

**Comment by denravonska** [comment]
@tomasbrod Which language do you mean?

**Comment by HuguesDohmen** [comment]
If translations in duch need to be done, I will give it a shot.

**Comment by tomasbrod** [comment]
@denravonska The Slovak language. Additionally there are multiple unused strings and, what is worse, a lot of duplicate strings in the locale files.

**Comment by denravonska** [comment]
@tomasbrod I assumed duplicate translations got merged by Qt Linguist but I might be wrong.

I've left the vanished leftover translations in the files for this translation run under the assumption that they were used by the tool to provide translation suggestions for new strings.

**Comment by denravonska** [comment]
I have added 26 translations which were in the source tree but not in the final build:

```
+        <file alias="af_ZA">locale/bitcoin_af_ZA.qm</file>
+        <file alias="be_BY">locale/bitcoin_be_BY.qm</file>
+        <file alias="bg">locale/bitcoin_bg.qm</file>
+        <file alias="bs">locale/bitcoin_bs.qm</file>
+        <file alias="ca">locale/bitcoin_ca.qm</file>
+        <file alias="ca@valencia">locale/bitcoin_ca@valencia.qm</file>
+        <file alias="cy">locale/bitcoin_cy.qm</file>
+        <file alias="es_MX">locale/bitcoin_es_MX.qm</file>
+        <file alias="es_UY">locale/bitcoin_es_UY.qm</file>
+        <file alias="et">locale/bitcoin_et.qm</file>
+        <file alias="eu_ES">locale/bitcoin_eu_ES.qm</file>
+        <file alias="fa_IR">locale/bitcoin_fa_IR.qm</file>
+        <file alias="hi_IN">locale/bitcoin_hi_IN.qm</file>
+        <file alias="id_ID">locale/bitcoin_id_ID.qm</file>
+        <file alias="kk_KZ">locale/bitcoin_kk_KZ.qm</file>
+        <file alias="ky">locale/bitcoin_ky.qm</file>
+        <file alias="la">locale/bitcoin_la.qm</file>
+        <file alias="lv_LV">locale/bitcoin_lv_LV.qm</file>
+        <file alias="ms_MY">locale/bitcoin_ms_MY.qm</file>
+        <file alias="sah">locale/bitcoin_sah.qm</file>
+        <file alias="sq">locale/bitcoin_sq.qm</file>
+        <file alias="sr">locale/bitcoin_sr.qm</file>
+        <file alias="th_TH">locale/bitcoin_th_TH.qm</file>
+        <file alias="ur_PK">locale/bitcoin_ur_PK.qm</file>
+        <file alias="vi_VN">locale/bitcoin_vi_VN.qm</file>
+        <file alias="vi">locale/bitcoin_vi.qm</file>
```

**Comment by denravonska** [comment]
Standalone Qt Linguist installers are available at https://github.com/lelegard/qtlinguist-installers/releases. This is probably the easiest way for translators to help.

**Comment by grctest** [comment]
Looks like there's a larger amount of translations available within the official bitcoin repo:
https://github.com/bitcoin/bitcoin/tree/master/src/qt/locale

It appears to use a different format, however we could pick and choose..

**Comment by mrip0001** [comment]
I will try the Chinese中文 translation

**Comment by mrip0001** [comment]
https://github.com/gridcoin/Gridcoin-Research/pull/404
I finished the Chinese中文 translation of Gridcoin格雷德币
