### ISSUE TITLE
whitelist poll for Sourcefinder

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [Erkan-Yilmaz/Gridcoin-tasks#128]
see our [8th interview](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2017_05_14.MD) (series: "talking with BOINC admins"):
* setting up a whitelist poll for: Duchamp Sourcefinder

cc @grctest

**Comment by tomasbrod** [comment]
Should wait for the release before creating new important polls.

**Comment by Foggyx420** [comment]
Sam seemed like a great guy behind this project and being his second at that I will support his whitelist once all things are running. It was a good interview for the duration I was there. Thumbs up.

**Comment by grctest** [comment]
I have created a thread on cryptocointalk for this project: https://cryptocurrencytalk.com/topic/83717-duchamp-sourcefinder/

As soon as the domain and SSL concerns are solved, I'll vote this in - I don't mind that it's only going to last 2 or 3 months, if we let our userbase know this then it's up to them to stake to access their owed funds in a timely fashion.

**Comment by Foggyx420** [comment]
I agree userbase should know the length limit and possible after the project is done maybe a few days of it staying online to give users a final chance to stake there reward could be good? Id see there being an issue if it finishes and its done and shutdown immediately as the last while of work wouldn't count and users may back off of the project during the last few days if they did get a DPoR in that time frame.

**Comment by sam6321** [comment]
As an update, the domain is now working, and we're using SSL: [](https://sourcefinder.theskynet.org/duchamp/)

**Comment by Foggyx420** [comment]
@sam6321 good job. the reCAPTCHA appears to be broken for signup "invalid domain for site key" Probably because of the domain change :) I can't sign up till that is corrected

**Comment by sam6321** [comment]
@Foggyx420 Just updated the reCAPTCHA domain. Would you be able to try again?

**Comment by Foggyx420** [comment]
@sam6321 works good now, thank you. all signed up. :)

**Comment by Foggyx420** [comment]
@grctest This ready to go?

**Comment by Erkan-Yilmaz** [comment]
added whitelist poll, see [here](https://steemit.com/gridcoin/@erkan/gridcoin-poll-should-we-add-sourcefinder-to-the-whitelist-vote-until-july-26)
* please vote in the next 2 weeks
