### ISSUE TITLE
7000 GRC bounty: solving superblock situation (6850 GRC) + creating superblock (150 GRC)

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [Erkan-Yilmaz/Gridcoin-tasks#136]
situation:
* last superblock: #934837, 98h 35 mins ago (2017-06-21 17:50:40)
* a superblock comes normally like every 24-48h

Why is this important?
* e.g. newcomers currently can not get rewarded or rewarded fairly (since their magnitude builds up at begin). The fair rewarding is also important, b/c people can just sit on their "free" magnitude which holds longer.

* a superblock is a combination of: 
  * 1. processing the BOINC stats for the day (e.g. it brings your new !magnitude; normally a !superblock comes every 26h-48h) and 
  * 2. registering CPID of new users. 

A "regular block" processes the transactions that have occurred in the network during the block's time frame

some investigation results:
* see latest comments in: https://github.com/gridcoin/Gridcoin-Research/issues/392

@barton2526: **250 GRC** pledged to whoever (or multiple if team effort) can solve the current superblock situation
@barton2526: and **50 GRC** to the wallet that stakes the superblock

**Comment by XaqFields** [comment]
xaqfields: 250 GRC pledged (additional to @Barton26) to whoever (or multiple if team effort) can solve the current superblock situation

xaqfields: 50 GRC pledged to the wallet that stakes the SB

**Comment by elspru** [comment]
How would someone go about fixing it?
i heard a theory that it is because people aren't staking their wallets.
my idea is that it is because of lots of new users.
the new user idea can be tested by if someone can see difference in number of cpids of previous superblocks and this one.

If there is a big difference in this one it could be the issue.
in which case team gridcoin could temporarily stop new members till the sb finishes synchronizing. Then reopen on the new block.

**Comment by jericomanapsal** [comment]
I pledge 100 GRC to whoever (or a set of people) solves this situation 😺

**Comment by Bouowmx** [comment]
I pledge 250 GRC to the person(s) who resolve, and 50 to the address that stakes the next superblock.

**Comment by Erkan-Yilmaz** [comment]
see also comments [here](https://steemit.com/gridcoin/@erkan/usdgrc-bounty)

**Comment by Editorial-Meat** [comment]
We have been trying to get our NN hashes to sync up in the developer's Slack. Even when we execute a NN sync through syncdpor2, and compare the hash after, we don't get the same hash. It could be due to the number of CPIDs changing, as we are not all returning the same number of CPIDs present in the network. We had numbers between 2199 and 2210.

Maybe it would be an option to buffer beacons near an expected superblock so the network come come to a consensus on the hash? The network is currently split about evenly on consensus between 3 different hashes, which is why no SB is forming. What is the consensus threshold?

**Comment by Editorial-Meat** [comment]
As another note, we currently have consensus on the hash:

"Neural Hash" : "Popularity,Percent %",
"213472e4b11ea3170e1a01323f309576" : "29; 99.97%",

But only 29 participants of the quorum trying to stake...? The chance of that is very small unless there just so happens to be a whale included.

**Comment by Editorial-Meat** [comment]
I think we need to set the quorum to have an entry criteria based on DPOR, so that we do not end up with a situation where once consensus IS FINALLY REACHED the chance to stake is about zero.

**Comment by dc7dgrid** [comment]
I want to raise the bounty: I pledge 1000 GRC to the person or team who will solve this issue.

**Comment by Erkan-Yilmaz** [comment]
thanks @dc7dgrid

I'll ask @barton2526 to set up a GRC address so people can send it to there

**Comment by AbuApellius** [comment]
Sorry for any lack of understanding; I'm new to gridcoin. 
Is the problem that there are not enough CPU cycles going to validate/generate the superblock? If that's the case, why not turn that task into a BOINC project?

**Comment by Vortac2** [comment]
I pledge 5000 GRC to the person(s) who resolve this

**Comment by Erkan-Yilmaz** [comment]
@Vortac2 thank you

**Comment by barton2526** [comment]
I have now set up an independent isolated INVESTOR wallet to hold the bounty funds and distribute them once the issue has been resolved.  This address is SD8bHkNcZeQqZFta4Us7EfMmperAbBeqAe

@XaqFields @jericomanapsal @Bouowmx @dc7dgrid @Vortac2

**Comment by Erkan-Yilmaz** [comment]
we have a NEW superblock ! 

getblockhash 942327 => b0354a55b11c02f2768c2a0368b0eff5ab2d8e7a1a5a4fb06dbada5826368d23

**Comment by barton2526** [comment]
Are we fully in agreement that 150 GRC should be sent to the staker and the remaining bounty should be held until a solution to the problem is developed or at least understood?  If so, I will pay out 50 GRC (myself) + 50 GRC (from @XaqFields).  I also hold @Vortac2's bounty but he did not specify to pay to the staker.  Please confirm on irc with me.

**Comment by barton2526** [comment]
150 GRC sent to staker of the superblock.  See here for tx:

https://www.gridcoinstats.eu/block/942483/33556f17ba480bc3763b9e93553ba64e7bd130849e9851a411081baf761a1843

**Comment by Erkan-Yilmaz** [comment]
likely causes of the delayed superblock + new Gridcoin version: 
* "Within a few days a leisure will be released aimed at adressing these 3 known issues"

https://steemit.com/gridcoin/@ravonn/gridcoin-superblock-we-forgive-you

**Comment by barton2526** [comment]
Additional 500 GRC sent to staker (250 from @Vortac2 and 250 from myself).  Bounty wallet is now at 6350 GRC for dev solution (pending leisure update(?))

**Comment by Quezacoatl1** [comment]
Thanks guys, I seem to be the lucky staker :)

**Comment by XaqFields** [comment]
Thanks @Quezacoatl1 for staking! That's the main thing we needed during this SuperBlock struggle was people to stake their coins. Enjoy your winnings :-)

**Comment by barton2526** [comment]
Regarding the 6750 GRC bounty still active: As holder of the escrow it's not ultimately my call, but I do not consider this leisure update to have satisfied the terms of "fixing the NN problem".  I would not feel comfortable paying out the bounty until a more stable and tested solution is put in place.  I would also prefer to wait several days to ensure said solution "holds" and we do not payout prematurely.  @bullshark @vortac @xaqfields @dc7dgrid @Bouowmx are free to disagree

If any bounty payer wishes me to send their bounty out at any time, just let me know.

**Comment by Erkan-Yilmaz** [comment]
more than 54h since the last superblock #951984
* seems the superblock fixes in [3.5.9.1](https://steemit.com/gridcoin/@erkan/new-release-gridcoin-version-3-5-9-1) (+ [3.5.9.2](https://steemit.com/gridcoin/@erkan/new-release-gridcoin-version-3-5-9-2-not-mandatory)) not working (fully) or 
* some more conditions need to be checked

**Comment by denravonska** [comment]
A lot of people are still running old nodes, still making it hard to reach consensus. On my wallet, only 37% (10/24) of the NN-capable connections are running 3.5.9.2.

**Comment by Erkan-Yilmaz** [comment]
"We had now 5 superblocks after this 148h-MEGA-long superblock #942327, and  the average and median times were about 33h (or in block terms: 1931 blocks and 2051 blocks)." ([We are waiting for you, oh SUPER-block... again](https://steemit.com/gridcoin/@erkan/we-are-waiting-for-you-oh-super-block-again))

**Comment by Vortac** [comment]
Man I was so confused by the few emails that I got tagged in. Don't forget to add that 2 onto Vortac. Best of luck to whatever this is.

**Comment by Erkan-Yilmaz** [comment]
after 62h there it is:

* superblock: #956235 (2017-07-07 13:00:00)

**Comment by vega40k** [comment]
i was the creater of this on. 
 superblock: #956235 (2017-07-07 13:00:00) i was so glad :-)

**Comment by barton2526** [comment]
As the current holder of this bounty, I think all of us should come to an agreement on what to do regarding these funds.  I can continue to hold them, they can be paid if you think the bounty has been met, or I can return the bounty to the donators.  Thoughts?  @XaqFields @jericomanapsal @Bouowmx @dc7dgrid @Erkan-Yilmaz @Vortac2

**Comment by tomasbrod** [comment]
The superblock situation definitely got better. But from a "Critical" to "Not so good".
When considering bounty, don't forget [PR 522](https://github.com/gridcoin/Gridcoin-Research/pull/522) (it takes effect at v8, if it helps, we don't know).

**Comment by Vortac2** [comment]
As a non-dev, I can't really decide how to split this bounty. Perhaps we should just forward it to the dev which contributes most hours under new Developer Reimbursement program (sort of an extra incentive).

**Comment by XaqFields** [comment]
I can't speak for everyone else, but my personal intention with donating to this bounty was more to fix the immediate issue we were having which caused SuperBlocks to take several days to be born. That seems to be fixed, even if it's not perfect. 

With that said, I'm comfortable with any disbursement you choose with my portion of the bounty. Whether that be right now, or later when more work has been done. I'm indifferent and put my trust in you @barton2526

**Comment by 3ullShark** [comment]
Although it was Rob who made all the changes to the VB code and implemented the harvester to make consensus easier. I think @Foggyx420 and @denravonska did a lot of research and testing on this issue and found the problem with the average mag not accepting the SB's.

**Comment by barton2526** [comment]
Would you guys be comfortable splitting the bounty between them?  If not I can return or withhold your portion.

**Comment by XaqFields** [comment]
100% okay on my end.

**Comment by barton2526** [comment]
So far 500/6500 agreed upon.  Waiting on: @jericomanapsal @Bouowmx @dc7dgrid @vortac2

**Comment by Vortac2** [comment]
I agree too - let my share go to @Foggyx420 and @denravonska.

**Comment by barton2526** [comment]
@denravonska Has requested that his half of the bounty be paid to iFoggz.  Is this acceptable @XaqFields @Vortac2?

**Comment by XaqFields** [comment]
What a nice guy --- absolutely.

**Comment by barton2526** [comment]
Current split (5200/6500 accounted for): 

80% (4160 GRC) to iFoggz
20% (1040 GRC) to @denravonska

**Comment by Vortac2** [comment]
I concur :)

**Comment by dc7dgrid** [comment]
Agreed!

**Comment by barton2526** [comment]
https://steemit.com/gridcoin/@barton26/6500-grc-superblock-bounty-will-be-paid-out-today

**Comment by barton2526** [comment]
Payment sent to iFoggz

**Comment by MagixInTheAir** [comment]
Should the issue be closed ?

**Comment by barton2526** [comment]
Still holding 300 GRC.  100 from @jericomanapsal and 200 from @Bouowmx.  If I do not receive a response in the next 3 days, I will return these funds to their respective donators.

**Comment by tomasbrod** [comment]
Oh, I remember Ravon  and iFoggz working really hard in the fight for superblock. I could only watch, because that stuff was too much for me. Rob is not being rewarded, because he already has enough? IIRC he did some programming too.

**Comment by dc7dgrid** [comment]
@tomasbrod How much do you think Rob should get? I would add some additional coins to the bounty to pay Rob for his work.

**Comment by Erkan-Yilmaz** [comment]
comment by QuintLeo [here](https://bitcointalk.org/index.php?topic=324118.msg21357229#msg21357229):
* "Dunno why this is being paid out, the superblock is BROKEN again and has BROKEN twice in the last week or so."

he is probably referring to [these 2 SBs](https://github.com/Erkan-Yilmaz/GRC/issues/44)

**Comment by barton2526** [comment]
@Bouowmx has requested his 200 GRC returned to him.  This has been done.  Still waiting to hear from @jericomanapsal.  They have 1 day left to respond before their funds will be returned.

**Comment by barton2526** [comment]
All funds from escrow have been emptied.  @Erkan-Yilmaz move to close issue.
