### ISSUE TITLE
make litebit.eu list Gridcoin

### ISSUE THREAD

**Issue by LifeEncrypter** [Erkan-Yilmaz/Gridcoin-tasks#139]
I contacted [LiteBit](https://www.litebit.eu/en) and asked them wether they would add Gridcoin to their exchange.
Since we got a qt wallet they would be able to, but they are charging a one-time fee of 0.25 BTC for adding new coins.

And copied from their response:
"What LiteBit has to offer
-Buying GRC
-Selling GRC
-Hosted wallet for GRC"

**Comment by Erkan-Yilmaz** [comment]
see also in the [forum](https://cryptocurrencytalk.com/topic/85089-make-litebiteu-list-gridcoin/)

**Comment by grctest** [comment]
If they add Gridcoin for free then it sounds good, I don't think we should be paying a bounty for an exchange that isn't listed on coinmarketcap: https://coinmarketcap.com/exchanges/volume/24-hour/all/

**Comment by Quezacoatl1** [comment]
It is not an exchange, it is a payment processor exchanging fiat to crypto and back. Like holytransactions.

**Comment by silent5am** [comment]
I have never heard of them. How trustworthy are they? How do they handle privacy/seecurity of customers, etc? Are there any reviews apart from those on their site (which could be fake)?

In general, are fees to list a currency and allow for trade a standard among all services?

Maybe get in contact with one of the more [popular/higher rated](https://www.bestbitcoinexchange.io/) services first and find out if they charge fees and/or what their conditions would be? Then compare with LiteBit and decide if it is a good move based on all the facts.

**Comment by fab-io** [comment]
just my 2 cent.

I've used it to buy some BTC and ETH, and so far no problems, BTW my experience is very limited.

Said that, I don't think we have to pay for being listed there, since they already earn applying a margin, for example at the moment of writing they sell BTC at €2302 while for Bitstamp BTC is at €2209.

**Comment by LifeEncrypter** [comment]
I also bought btc a few times from them. Only for a little more than 50€, but i had absolutly no problems.

**Comment by xPh03n1x** [comment]
I just tried using them to get some BTC, which in turn I'd convert into GRC, but their payment options are rather limited and not as flexible as advertised. Although CC payments are advertised, it doesn't seem like you can use a card issued by US bank.

I agree that paying 0.25 BTC to be listed there doesn't seem to be worth it at the moment.
