### ISSUE TITLE
poll: Should BOINC contribution again affect stake weight?

### ISSUE THREAD

**Issue by tomasbrod** [Erkan-Yilmaz/Gridcoin-tasks#151]
Title: Should BOINC contribution again affect stake weight?

Description: Recent release of Gridcoin removed effect of Magnitude from stake weight thus making the chain consensus Proof of Stake only (for security reasons). Should developers work towards  shortening the time less rich miners must wait to get a reward and restoring their share in securing the block chain.

Options:
1. Keep the consensus PoS only
2. Shorten the time to get a reward
3. Give BOINCers share in securing the blockchain
4. Abstain (I don't understand/know/care)

Note: This poll is purposely kept less technical, partly because we don't have concrete proposal how to 
do either, and to allow less immersed to vote.

#45

**Comment by grctest** [comment]
Is the poll online yet?

Abstain option?

**Comment by tomasbrod** [comment]
I closed this request, because this poll failed its main goal, to be understandable for general public and not misleading.
