### ISSUE TITLE
Gridcoin Community Organization

### ISSUE THREAD

**Issue by tomasbrod** [Erkan-Yilmaz/Gridcoin-tasks#155]
**[Gridcoin-Community Organization is on GitHub](https://github.com/gridcoin-community)**

* test what organization repositories can provide in terms of permission
* try managing issues
* try branch restrictions
* design a team structure
  * releasers
  * developers
  * issue organizators
* think about moving Tasks and Issues to the organization

**Comment by tomasbrod** [comment]
Testing transfer of https://github.com/tomasbrod/transfer-org-test to community.

Settings -> transfer:
 * type name of the repo
 * type "gridcoin-community"
 * click confirm.

"Team access" dialog page comes up with checkbox near each team in the org.
* I select only "Gridcoin-Research Development Team"
* click transfer
* it tells me that it can take few minutes, but is complete almost instantly

I opened the transferred repo and inspect what is:
* branches and all commits are ok, as that is backed by git, not github
  * git content can be even transferred to other git hosting easily
* issues, prs, tags and assigments are intact
* labels, milestones and wiki pages are ok too
* I can still assign and create tags and milestones
* i can assign issues to all team members
* BUT I can no longer access the "Settings" menu
  * it seems like I lost the admin privileges
  * but if I create repo straight under the community, i can access "Settings"

**Comment by tomasbrod** [comment]
When the gridcoin repo is put under organization and the development team granted write access to it, protected branches must be set-up to protect `master`, `staging` and probably `development` branches from unathorized modification by any team member.

I suggest creating another team "Executive team", for now containing only Rob @gridcoin and Marco @denravonska, which members only have permission to push or merge to `master`.

**Comment by tomasbrod** [comment]
I think this repository should go first to the organization, as en example. There already is already a [Task maintainers team](https://github.com/orgs/gridcoin-community/teams/tasks-maintenance/members).

**Comment by tomasbrod** [comment]
A issue-only repository should be created in the organization, for the purpose of collecting requests for team membership and repo settings changes. Such repo should be owned by "Executive team", which is also responsible for approving critical changes and releases.

**Comment by grctest** [comment]
> I think this repository should go first to the organization, as en example. There already is already a Task maintainers team.

https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/150

Should be simple enough to do, just needs @Erkan-Yilmaz to click a couple buttons.
