### ISSUE TITLE
join again BeyondBitcoin hangouts

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [Erkan-Yilmaz/Gridcoin-tasks#25]
assigning to @grctest

requirement:
* high upvote on steemit

mentioned in [hangout 22](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2017_01_21.MD):

**Comment by Erkan-Yilmaz** [comment]
done: 
https://steemit.com/beyondbitcoin/@officialfuzzy/guest-signups-beyond-bitcoin-hangout-192-1-27-17-rsvp-to-guest-speak-about-your-blockchain-project-last-week-s-payouts-signups

**Comment by grctest** [comment]
Anything to add to the hangout post?
Have I missed anything?

**Comment by Erkan-Yilmaz** [comment]
see #92
