### ISSUE TITLE
create DrugDiscovery@home challenge

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [Erkan-Yilmaz/Gridcoin-tasks#29]
length: 3 days ? or more ?

task: @grctest

mentioned in [hangout 22](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2017_01_21.MD):

**Comment by grctest** [comment]
"Your team doesn't have the required minimum number of active members (2) in the selected project!"

An issue is preventing the creation of a DD@H challenge on boincstats!
