### ISSUE TITLE
make coinvert accept GRC 

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [Erkan-Yilmaz/Gridcoin-tasks#32]
People should contact them (tweets, email, ...) to bring attention to this.

mentioned in [hangout 22](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2017_01_21.MD): 

related: #24 #31

**Comment by grctest** [comment]
Link: https://coinvert.io/

**Comment by droplister** [comment]
Coinvert is a scam. They use ShapeShift. They'll facilitate your small trades and then take your large ones. They'll tell you you'll get a refund in 48 hours and then it never comes and they stop replying. Avoid!

Happened to me. Here are other reports:
https://steemit.com/bitcoin/@anarchrysalis/my-awful-coinvert-experience
https://www.reddit.com/r/btc/comments/5wvv7g/coinvertio_scam_warning/

**Comment by grctest** [comment]
Thanks @droplister for providing this information, this is incredibly disappointing!

Let's find alternative platforms!
