### ISSUE TITLE
contact Katie (her server causing Windows users to not stake due to clock off issue?)

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [Erkan-Yilmaz/Gridcoin-tasks#36]
it seems: Windows users can not create blocks due to clock off issue :-(
* further info: https://cryptocointalk.com/topic/52040-clock-issues/
* pic: https://github.com/gridcoin/Gridcoin-Research/issues/186

It's not clear yet from where this originates, but it is not @grctest 's servers

so: Katie ?
* also her irc bot has RPC trouble. her wallet not running perhaps ?

to be clear this is just a thought, don't go witch-hunting :-(

mentioned in [hangout 22](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2017_01_21.MD):

**Comment by TG13088** [comment]
RPC's are usually time-stamp dependent and require some relative degree of synchronization.  All systems using RPC's should use a common time methodology such as __NTP__ or __SNTP__.  Thought must be given to using local time or more probably, preferably GMT/UTC.  This would aid support staff by eliminating the need to convert to GMT/UTC while matching Messaging/Events across the multiple servers.

**Comment by grctest** [comment]
Has anyone reached out to katiee then? I don't think she's running a full node TBH..

If she's not on IRC, she's on Steam: https://steamcommunity.com/id/Kati3e

**Comment by RononDex** [comment]
Any update on this? My fullfillment has been at 0% for 2 days now because of this bug

**Comment by grctest** [comment]
It's not katiee's server, the time diagnostics uses: 

>  Dim sNISTHOST As String = "time-nw.nist.gov" 'Atomic Clock Time Server in UTC

https://github.com/gridcoin/Gridcoin-Research/blob/4efc4a1abe85f69dcca4e6b95154226ba9f9ff64/contrib/Installer/boinc/boinc/GRCDiagnostics.vb#L10

Where did people get the impression this had anything to do with katiee? lol...
