### ISSUE TITLE
C-CEX in maintainance mode

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [Erkan-Yilmaz/Gridcoin-tasks#37]
OK: it seems buy/sell inside C-Cex works.

but user reports his "grc wallet" at the exchange shows maintainance mode :-(

I told the user on reddit who reported this to contact the exchange itself
we agreed to wait until he gives feedback

but: ofc, someone else also can contact C-Cex additionally. thx
they have:
* irc channel
* ticket system

further info: [reddit](https://www.reddit.com/r/gridcoin/comments/5p4qwf/gridcoin_wallet_on_ccex_in_maintenance_mode/)

mentioned in [hangout 22](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2017_01_21.MD):

**Comment by Erkan-Yilmaz** [comment]
@fkinglag contacted CCEX support also. thx

**Comment by grctest** [comment]
That's both Poloniex and C-Cex that have recently performed unexplained maintenance on their wallets, poloniex has raised their minimum verifications to something odd like 150. Perhaps it was due to the [low stake weight issue raised on the gridcoin-research repo](https://github.com/gridcoin/Gridcoin-Research/issues/106)?

**Comment by TG13088** [comment]
My research has shown that Poloniex doesn't do business in the US due to regulations.  Bittrex doesn't do business with NY State customers due to NY laws and C-Cex has "interesting" procedures that basically drive you to a premium account due to their verification mechanisms.

**Comment by startailcoon** [comment]
> C-Cex has "interesting" procedures that basically drive you to a premium account due to their verification mechanisms.

What do you mean with this? Are you referring to US customers? I've used C-Cex for a long time and have never had any issue with them, but I'm also not a US residence.

**Comment by grctest** [comment]
Perhaps for depositing/withdrawing FIAT? I've never had to do any kind of verification on c-cex before. If you're worried about verification, you should be using BitSquare & Bitshares.

**Comment by startailcoon** [comment]
I've never used C-cex for FIAT currency, so that could be the issue maybe. I tried once, but gave up on it sine I have other places that provide a good experience for exchanging.

**Comment by pavulon18** [comment]
I believe I am the one Erkan-Yilmaz was referring too about the gridcoin wallet being off-line.

I did finally receive a response from C-CEX.

"We are waiting for fix from dev."

That was the response from them in its entirety.

**Comment by Erkan-Yilmaz** [comment]
fkinglag: "CCEX wallet appears to have been working again for the past few days, cheers."
