### ISSUE TITLE
Open-source Gridcoin website development

### ISSUE THREAD

**Issue by grctest** [Erkan-Yilmaz/Gridcoin-tasks#44]
https://github.com/grctest/Gridcoin-Site

# The Gridcoin.US website has been open-sourced.

The removal of designmodo's startup-framework has resulted in a lack of CSS, JS and html container/class id's --> The website is glitchy looking, needs tome TLC.

It uses the [MiddleMan Static Site generator](https://middlemanapp.com/) to minimize duplicate code.

I quickly integrate suitable pull-requests.

Barton26 has helped out recently.

-----

## Xubuntu guide:

sudo apt-get install ruby-dev

sudo apt-get install nodejs

sudo gem install middleman

sudo apt-get install git

sudo apt-get install build-essential

git clone https://github.com/grctest/Gridcoin-Site.git

cd Gridcoin-Site

bundle install

bundle exec middleman server

**Comment by Erkan-Yilmaz** [comment]
cc @barton2526

**Comment by barton2526** [comment]
I'll be adding to this when I have the time.  Working down the issue list I set up previously.  If anyone has any suggestions feel free to add to the list.
