### ISSUE TITLE
Optimize resource consumption of image files in wallet

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [Erkan-Yilmaz/Gridcoin-tasks#50]
"going through the resource consumption of image files. Coz images take up mo' space than code."

@Peppernrino is doing this task today

mentioned in [hangout 2](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2016_08_13.MD):

**Comment by grctest** [comment]
Related:
https://github.com/gridcoin/Gridcoin-Research/pull/103
https://github.com/gridcoin/Gridcoin-Research/pull/102

**Comment by Peppernrino** [comment]
it's all done. just learning how to use git properly so i don't make a commit per picture. :P

**Comment by Peppernrino** [comment]
i also took the liberty of remastering the soundtrack for Galaza. it will now play on more soundcard types, sounds better, bgm is now properly syncopated, and the sound effects will be more performant. total size reduced from 1.64MB to 412KB. :)

**Comment by Peppernrino** [comment]
https://github.com/gridcoin/Gridcoin-Research/pull/201

**Comment by denravonska** [comment]
I will merge it as soon as I can build and test in Windows.

**Comment by Peppernrino** [comment]
pull request accepted in development branch. 👍
