### ISSUE TITLE
Approach BOINC account manager & POW pool devs about helping us with opensource pool

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [Erkan-Yilmaz/Gridcoin-tasks#54]
Approaching e.g. 
* Gridrepublic, BAM, charityengine, ... 
* existing POW pools

if they can opensource their software or help us for: #2
The bounty could motivate them now, previously we had no bounty.

mentioned in [hangout 3](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2016_08_20.MD): 2:00:00

**Comment by grctest** [comment]
They may help slightly out, but I highly doubt they'll open source their account managers :/

**Comment by startailcoon** [comment]
I think we are better of experimenting with the software and setting it up ourselves from the ground up. I have showed interest in the forum, but I'm having this a long term goal for the moment (6+ months). When time gives I will do some reading and experiments.

**Comment by grctest** [comment]
Considering BGB has almost finished the open-source pool I think we can close this issue whilst keeping #2 open.
