### ISSUE TITLE
Cold staking to increase staking participation

### ISSUE THREAD

**Issue by skcin** [Erkan-Yilmaz/Gridcoin-tasks#68]
Besides a fixed stake reward there is another thing that could help and that is cold staking. 
If we could implement cold staking it would be much easier to keep staking 24/7. The best practise is to not stake on a full node because of security issues. What if we could eliminate these security issues.

The https://www.nem.io/ crypto currency has a even better system where you can stake without risk on unsecure systems. They call it delegated harvesting and it allows you to stake on a remote server without your wallet leaving your local pc.

**Comment by grctest** [comment]
How difficult would it be to port this from NEM to GRC though? Isn't NEM NodeJS based? How difficult is this to use for an average user?

I think that NXT has a similar feature where they're able to give their stake weight to someone else to stake with, which would potentially increase stake weight participation but would promote centralized entities.

**Comment by skcin** [comment]
The problem with porting from nem or nxt is that they do not share a code base with bitcoin. I think they were written from scratch.  I don't know if there is something similar in bitcoin derived cryptocurrencies.

It is rather easy to set up, and for those who set up their own remote servers it should be no problem.

**Comment by grctest** [comment]
>The problem with porting from nem or nxt is that they do not share a code base with bitcoin. I think they were written from scratch.

Indeed, it's completely incompatible code & would require original development on a similar concept.
