### ISSUE TITLE
IRC !rain news/announcements

### ISSUE THREAD

**Issue by fkinglag** [Erkan-Yilmaz/Gridcoin-tasks#71]
Could/would we be able to provide a way for a news/announcement-raining ability in IRC? I tend to use sEp's tipbot in IRC for raining Gridcoins on users. Sometimes I will use the rain to get users to read some important news or announcements for Gridcoin. Maybe we could get a new rain-specific news/announcement bot online? Or maybe we could already use Fediverse, if Erkan is willing?

**Comment by grctest** [comment]
By !rain 80 80, you can effectively ping the entire channel. If users get the notification they may open the client & read the surrounding messages (to which you could include the news there).

A new rain message along the lines of [latest news articles][rain message] in the one line would split across multiple message but the first message could display in mobile notifications.

I think using the @all command in telegram and slack is a far more effective ping, as it's free and isn't split across multiple lines + higher mobile notification support for telegram/slack clients.

Don't go too crazy with the @all command though ;D

**Comment by fkinglag** [comment]
Ah, good to know about the slack channel's @all command. :)

I will have to use the @all highlight in moderation. On the other hand this is one expensive way of highlighting users. I think it will be effective to get users scrolling back through their chat if they're idle, too. Thank you, Erkan, for informing me in IRC about the !upvote command because it will be really helpful. 

For now I will have to do my IRC highlighting and news sharing by hand. Not sure how much we all would want multiple tip-bots, by the way. The slack and telegram channel aren't as active and populated as #gridcoin is on Freenode.

I'll eventually try to make an attempt at setting up and scripting a bot for this. That will be later. I'll update this issue with development as it follows. :D

**Comment by Erkan-Yilmaz** [comment]
will be done by fedi, @fkinglag and me are discussing this right now

**Comment by grctest** [comment]
> The slack and telegram channel aren't as active and populated as #gridcoin is on Freenode.

Whilst true, one does not leave said chat rooms when disconnected, unlike in IRC.

**Comment by Erkan-Yilmaz** [comment]
fedi offers now !newsrain and !reward
(help with: !newsrain help, !reward help)

**Comment by Erkan-Yilmaz** [comment]
closed: see hangout 23 discussion
