### ISSUE TITLE
create a 3-day-long SRBase challenge

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [Erkan-Yilmaz/Gridcoin-tasks#80]
@grctest 
talked about it in [hangout #23](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2017_02_04.MD)

**Comment by grctest** [comment]
Idd, their web server is not capable of holding more than 3 days worth of workunits. I'll look into it in the near future.

**Comment by Erkan-Yilmaz** [comment]
announced also: http://srbase.my-firewall.org/sr5/forum_thread.php?id=743
