### ISSUE TITLE
presentation about blockchain for usage in the German/European energy market (April 7)

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [Erkan-Yilmaz/Gridcoin-tasks#91]
further info:
* [forum](https://cryptocointalk.com/topic/52937-strommarkttreffen-april-7/)
* in [hangout 26](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2017_03_18.MD)

tasks people can help with:
* check slides
* upload (to be done by @Quezacoatl1): presentation + possible audio of this

**Comment by Erkan-Yilmaz** [comment]
slides here: https://cryptocointalk.com/topic/1331-new-coin-launch-announcement-grc-gridcoin/page-1231#entry235529

**Comment by Erkan-Yilmaz** [comment]
[here](https://twitter.com/GridcoinIRC/status/850293201365815298)'s a pic about the presentation (showing the PoR slide)

**Comment by grctest** [comment]
Was there any recorded footage from this event?

**Comment by Erkan-Yilmaz** [comment]
> Was there any recorded footage from this event?

@Quezacoatl1 wrote in forum no audio recording made
