### ISSUE TITLE
check services that use Gridcoin if they experience problems (out of sync, ...)

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [Erkan-Yilmaz/Gridcoin-tasks#95]
Let's help the services which use Gridcoin (exchanges, ...) about [wallet does not sync](https://github.com/gridcoin/Gridcoin-Research/issues/246):

<br><br>
I. results from below so far about service's wallets **working fine** (status from Friday): 
* CCEX
* coinpayments (replied with a correct hash)
* OpenLedger
* Poloniex

<br><br>
II. how you can help?
* 1: go to the services/exchanges/... not listed above, e.g.
  * https://poloniex.com/exchange/btc_grc
  * https://c-cex.com/?p=grc-btc
  * https://bittrex.com/Market/Index?MarketName=BTC-GRC
  * https://cryptofresh.com/a/OPEN.GRC
  * Bitsquare
  * eobot
  * ...
* 1a: send 1 or so GRC there, to see if it gets to the exchange
* 1b: since I don't know how their internal works: 
  * let's also transfer some GRC from there to your own wallet back

* 2: for service where you can't do step 1a and 1b, send an email to their support please:
  * coinpayments
  * Coinomi
  * crypto-games

III. before doing so, please make sure you are not on a [!fork](https://cryptocointalk.com/topic/50958-dpp-and-dpr/)
* e.g. currently: verify you have the hash: c835eb770c41da67b5a95c63c12b627c213b7419410d908f57277e68f77c514c 
  * with: **getblockhash 854338** (from the Gridcoin debug menu)

IV. post your result below, thx

**Comment by Erkan-Yilmaz** [comment]
I will now contact:
Openledger, coinpayments, Coinomi

**Comment by Erkan-Yilmaz** [comment]
CCEX:
* user BS says: sending works to there

**Comment by bryhardt** [comment]
Sent to polo 20 minutes ago, nothing yet. (was fine two days ago for me)

**Comment by grctest** [comment]
>Sent to polo 20 minutes ago, nothing yet. (was fine two days ago for me)
Poloniex does have a large confirmation period though, check the wallet status on the exchange and multiply the conf quantity by 90secs to get the est time of availability on exchange (20mins is within conf window).

**Comment by bryhardt** [comment]
Polo should show the deposit in the balances history with how many confirmations to go once it is received. Usually that happens in less than 10 minutes.

**Comment by Erkan-Yilmaz** [comment]
@bryhardt thx I have now created a ticket at Poloniex' help system, just in case

**Comment by Erkan-Yilmaz** [comment]
OK: coinpayments replied with a correct hash

**Comment by grctest** [comment]
OpenLedger is functioning fine too.

**Comment by bryhardt** [comment]
Not sure if they processed something on your ticket. Polo showed up now showing 52 of 120 confirmations.

**Comment by Erkan-Yilmaz** [comment]
> Not sure if they processed something on your ticket. Polo showed up now showing 52 of 120 confirmations.

* no reply by Poloniex yet
* since you see confirmations, it seems good
*we'd need now also a withdraw from Poloniex + don't need to worry about them anymore :-)

**Comment by bryhardt** [comment]
polo withdraw is good

**Comment by Erkan-Yilmaz** [comment]
> polo withdraw is good
thank you, @bryhardt

**Comment by Erkan-Yilmaz** [comment]
sent mail to BitSquare + BITTREX

**Comment by Erkan-Yilmaz** [comment]
bittrex's blockchain is 2 blocks behind mine, but it's a good sign...
* https://www.bittrex.com/status

**Comment by Erkan-Yilmaz** [comment]
eobot:
* sent email

**Comment by Erkan-Yilmaz** [comment]
crypto-games.net have issues :-(
https://cryptocointalk.com/topic/53202-gridcoin-wallet-sync-problems/

**Comment by grctest** [comment]
----

Ok, new task! We need to get all exchanges and services to enter maintenance mode ASAP, there's going to be a mandatory upgrade tonight!

Checklist:
Coinpayments
Cointopay
Coinomi
Poloniex
C-cex
Bittrex
Bitsquare (I don't think they actually run the client though... you hold your own funds, minus BTC).
Openledger
HolyTransactions

Less critical:
GRCPOOL.COM
Katiee's pool
Gridcoinstats
gridresearchcorp
explorer.gridcoin.asia
Cryptogames

**Comment by Erkan-Yilmaz** [comment]
done so far:
* Poloniex: added to existing ticket #107557 (which still had no reply)
* CoinPayments.net: new ticket #17544
* BITTREX (email to support)
* Coinomi: add to existing ticket #74223056 (which still had no reply)

**Comment by Erkan-Yilmaz** [comment]
message by main developper [here](https://cryptocointalk.com/topic/1331-new-coin-launch-announcement-grc-gridcoin/page-1233#entry235946)

**Comment by Erkan-Yilmaz** [comment]
[here](https://cryptocointalk.com/topic/1331-new-coin-launch-announcement-grc-gridcoin/page-1235#entry236082) is a summary of the last days with Gridcoin's chains

**Comment by Erkan-Yilmaz** [comment]
[Holytransaction](https://gridcoin.holytransaction.com) is NOT on the A chain

**Comment by darbon** [comment]
1. The HolyTransaction explorer does not use the same daemon as the wallet
2. The withdrawal is disabled and we are waiting for it to be safe to activate it
3. We are already in the A chain

**Comment by Erkan-Yilmaz** [comment]
@darbon thx for the info

@all
discussion: 
* [When should we begin to tell the services/exchanges to go "back to business" with Gridcoin ?](https://cryptocointalk.com/topic/1331-new-coin-launch-announcement-grc-gridcoin/page-1235#entry236137)

**Comment by grctest** [comment]
---

Ok, new task! We need to get exchanges and services to upgrade and verify connectivity & identical blockchain.

Checklist:
Coinpayments - ?
Cointopay - Emailed
Coinomi - Emailed, DM'd on Twitter.
Poloniex - Added info to ticket, no response yet. Mods not responding 
C-cex - raised a new ticket.
Bittrex - ?
Bitsquare - ?
Openledger - Emailed BlockTrades devs
HolyTransactions - Good (See above)
Cryptogames - Upgraded successfully https://cryptocointalk.com/topic/53202-gridcoin-wallet-sync-problems/#entry235962
Eobot - ?

Less critical:
GRCPOOL.COM - ?
Katiee's pool - ?
Gridcoinstats - Upgraded, on good chain.
gridresearchcorp - Upgraded, on good chain.
explorer.gridcoin.asia - Upgraded, needs further analysis of blockchain validity.

**Comment by Erkan-Yilmaz** [comment]
sent ALIEN's template to:
* Coinpayments
* Bittrex
* Bitsquare
* Eobot

**Comment by bryhardt** [comment]
For grcpool.com, it has been running on .7 for about 24 hours and everything seems okay. My personal windows client isn't working, but I'll have to deal with that next week. :)

**Comment by Erkan-Yilmaz** [comment]
I've contacted now:
Bittrex
Eobot
Coinpayments
Coinomi
Poloniex
Cointopay
C-cex
HolyTransactions ( cc @darbon )
Bitsquare
Cryptogames

already uptodate.
* gridcoinstats
* explorer.gridcoin.asia

in progress:
* Openledger

todo:
* GRCpool
* Katiee's pool
* gridresearchcorp

**Comment by Erkan-Yilmaz** [comment]
I've contacted now to go into maintainance mode:
Poloniex
C-cex
Bittrex
Eobot
Coinpayments
Coinomi
Cointopay
HolyTransactions ( cc @darbon )
Openledger
Bitsquare
Cryptogames

todo/inprogress:

gridcoinstats
explorer.gridcoin.asia
GRCpool
Katiee's pool
gridresearchcorp

**Comment by Erkan-Yilmaz** [comment]
further info [here](https://cryptocointalk.com/topic/1331-new-coin-launch-announcement-grc-gridcoin/page-1240#entry236591)

**Comment by grctest** [comment]
It has been about 4 days since we last had instability in the blockchain, c-cex has gone back to production. Should we get the other services notified to go live but with an increased min conf amount?

**Comment by Quezacoatl1** [comment]
I agree we should contact exchanges now.

**Comment by Quezacoatl1** [comment]
Contacting services now:

Coinpayments -
Cointopay - 
Coinomi -
Poloniex - 
C-cex - 
Bittrex - Contacted bittrex-richie in IRC
Bitsquare -
Openledger - 
HolyTransactions -
Cryptogames - 
Eobot - 

[List will be filled]

**Comment by grctest** [comment]
I have contacted Blocktrades.US (not IO), waiting to hear back from them.

**Comment by darbon** [comment]
[HolyTransaction](https://holytransaction.com) activated Gridcoin again yesterday.

**Comment by Erkan-Yilmaz** [comment]
@darbon 

> HolyTransaction activated Gridcoin again yesterday.

thx

could you also check [your block explorer](https://gridcoin.holytransaction.com/) ? it seems on a fork still

**Comment by nateonthenet** [comment]
@Quezacoatl1 Any followup re: Poloniex? The wallet is still disabled as of now.

**Comment by darbon** [comment]
@Erkan-Yilmaz We are reindexing the [Gridcoin's block explorer](https://gridcoin.holytransaction.com). Thanks for what you are doing for the community.

**Comment by Pascal666** [comment]
Poloniex still shows "Temporarily Disabled".  I opened a support ticket on Monday 4/10.  Just heard back:

Thank you for getting in touch and please accept my apologies for the delay.

We have been in contact with the developer and now hope to have this enabled shortly. Sorry for any inconvenience.

**Comment by FifthGB** [comment]
Nice

**Comment by Erkan-Yilmaz** [comment]
sent mail to EOBOT, b/c still not enabled.

https://www.eobot.com/status.aspx
Deposit Wallets	GRC offline - DOGE/BCN/XMR delayed
Withdraw Wallets	GRC/BCN offline

**Comment by grctest** [comment]
Any contact with poloniex recently? They've disabled withdrawls/deposits again... 👎

**Comment by sodom89** [comment]
At poloniex gridcoin withdrawls/deposits are still disabled.

**Comment by Erkan-Yilmaz** [comment]
Poloniex allows deposit/withdraw again
